name: Update Ratings

on:
  schedule:
    # every 14 days
    - cron: "0 15 3 * *"

  # can be triggered manually
  workflow_dispatch:

jobs:
  update_ratings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15

      - run: cd src && nix develop
      - run: python update_reviews.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.0
        with:
          message: update data.yaml via update_reviews.py
