name: Update Ratings

on:
  schedule:
    # every 14 days
    - cron: "0 15 3 * *"

  # can be triggered manually
  workflow_dispatch:

jobs:
  update_ratings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - run: echo $PATH

      - run: cd src && nix develop -c which chromium

      - name: Run update_reviews.py
        run: cd src && nix develop -c python update_reviews.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.0
        with:
          message: update data.yaml via update_reviews.py
