name: Update Readme and Map

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Update Ratings"]
    branches: [main]
    types:
      - completed

jobs:
  update_readme_and_map:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Run create_readme.py
        run: cd src && nix develop .#readmeAndMap -c python create_readme.py

      - name: Run create_map_data.py
        run: cd src && nix develop .#readmeAndMap -c python create_map_data.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.0
        with:
          message: update readme.md via create_readme.py
