name: Update Readme and Map

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Update Ratings"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15

      - run: cd src && nix develop
      - run: cd src && pwd && python create_readme.py
      - run: cd src && python create_map_data.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.1.0
        with:
          message: update readme.md via create_readme.py
